services:
  data:
    build: ./
    volumes:
      - app:/var/www/app
    depends_on:
      - nginx
      - php
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - app:/var/www/app
  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - app:/var/www/app
  mysql:
    image: mysql:8.4
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: development
      MYSQL_USER: development
      MYSQL_PASSWORD: development
  redis:
    image: redis:7.2
    expose:
      - 6379

volumes:
  app:
    name: app
  database:
    name: database